services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=PLMqaz2901
      - POSTGRES_USER=anuj
      - POSTGRES_DB=practice
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://anuj:PLMqaz2901@postgres:5432/practice

volumes:
  postgres_data: