services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=PLMqaz2901
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:PLMqaz2901@postgres:5432/postgres

volumes:
  postgres_data: